[package]
name = "dft_receiver"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies] 
dft_types = { path = "../dft_types" }
ic-cdk = "0.3.0"
ic-cdk-macros = "0.3.0"
candid = "0.6.21"

